version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: gitvizz-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/var/log/nginx
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - gitvizz-network
    restart: always
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gitvizz-backend
    env_file:
      - ./scripts/env-templates/backend.env.production
    environment:
      - PHOENIX_COLLECTOR_ENDPOINT=http://phoenix:6006/v1/traces
    volumes:
      - backend-storage:/data/storage
    depends_on:
      mongo:
        condition: service_healthy
      phoenix:
        condition: service_started
    networks:
      - gitvizz-network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8003/health || python -c \"import urllib.request; urllib.request.urlopen('http://localhost:8003/health')\" || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_BACKEND_URL=https://gitvizz.sutools.app
    container_name: gitvizz-frontend
    env_file:
      - ./scripts/env-templates/frontend.env.production
    depends_on:
      - backend
    networks:
      - gitvizz-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongo:
    image: mongo:7.0
    container_name: gitvizz-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ADMIN_PASSWORD:-defaultpassword}
      MONGO_INITDB_DATABASE: gitvizz_prod
    volumes:
      - mongo-data:/data/db
      - ./mongo/backup:/backup
    networks:
      - gitvizz-network
    restart: always
    # Remove --auth command to allow proper initialization
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  phoenix:
    image: arizephoenix/phoenix:latest
    container_name: gitvizz-phoenix
    environment:
      - PHOENIX_WORKING_DIR=/mnt/data
    volumes:
      - phoenix-data:/mnt/data
    networks:
      - gitvizz-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6006"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  gitvizz-network:
    name: gitvizz-network
    driver: bridge

volumes:
  mongo-data:
    name: gitvizz-mongo-data
  phoenix-data:
    name: gitvizz-phoenix-data
  backend-storage:
    name: gitvizz-backend-storage
