// This file is auto-generated by @hey-api/openapi-ts

import { type Options as ClientOptions, type TDataShape, type Client, formDataBodySerializer } from '@hey-api/client-fetch';
import type { GenerateTextEndpointApiGenerateTextPostData, GenerateTextEndpointApiGenerateTextPostResponses, GenerateTextEndpointApiGenerateTextPostErrors, GenerateGraphEndpointApiGenerateGraphPostData, GenerateGraphEndpointApiGenerateGraphPostResponses, GenerateGraphEndpointApiGenerateGraphPostErrors, GenerateStructureEndpointApiGenerateStructurePostData, GenerateStructureEndpointApiGenerateStructurePostResponses, GenerateStructureEndpointApiGenerateStructurePostErrors } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Generates LLM-friendly text from a code repository.
 */
export const generateTextEndpointApiGenerateTextPost = <ThrowOnError extends boolean = false>(options?: Options<GenerateTextEndpointApiGenerateTextPostData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<GenerateTextEndpointApiGenerateTextPostResponses, GenerateTextEndpointApiGenerateTextPostErrors, ThrowOnError>({
        ...formDataBodySerializer,
        url: '/api/generate-text',
        ...options,
        headers: {
            'Content-Type': null,
            ...options?.headers
        }
    });
};

/**
 * Generates a dependency graph from a code repository.
 */
export const generateGraphEndpointApiGenerateGraphPost = <ThrowOnError extends boolean = false>(options?: Options<GenerateGraphEndpointApiGenerateGraphPostData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<GenerateGraphEndpointApiGenerateGraphPostResponses, GenerateGraphEndpointApiGenerateGraphPostErrors, ThrowOnError>({
        ...formDataBodySerializer,
        url: '/api/generate-graph',
        ...options,
        headers: {
            'Content-Type': null,
            ...options?.headers
        }
    });
};

/**
 * Generates the file structure and content of a code repository.
 */
export const generateStructureEndpointApiGenerateStructurePost = <ThrowOnError extends boolean = false>(options?: Options<GenerateStructureEndpointApiGenerateStructurePostData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<GenerateStructureEndpointApiGenerateStructurePostResponses, GenerateStructureEndpointApiGenerateStructurePostErrors, ThrowOnError>({
        ...formDataBodySerializer,
        url: '/api/generate-structure',
        ...options,
        headers: {
            'Content-Type': null,
            ...options?.headers
        }
    });
};