// This file is auto-generated by @hey-api/openapi-ts

/**
 * Body_generate_graph_endpoint_api_generate_graph_post
 */
export type BodyGenerateGraphEndpointApiGenerateGraphPost = {
    /**
     * Repo Url
     * URL to a downloadable ZIP of the repository.
     */
    repo_url?: string | null;
    /**
     * Branch
     * Branch for GitHub repo URL.
     */
    branch?: string | null;
    /**
     * Zip File
     * A ZIP file of the repository.
     */
    zip_file?: (Blob | File) | null;
};

/**
 * Body_generate_structure_endpoint_api_generate_structure_post
 */
export type BodyGenerateStructureEndpointApiGenerateStructurePost = {
    /**
     * Repo Url
     * URL to a downloadable ZIP of the repository.
     */
    repo_url?: string | null;
    /**
     * Branch
     * Branch for GitHub repo URL.
     */
    branch?: string | null;
    /**
     * Zip File
     * A ZIP file of the repository.
     */
    zip_file?: (Blob | File) | null;
};

/**
 * Body_generate_text_endpoint_api_generate_text_post
 */
export type BodyGenerateTextEndpointApiGenerateTextPost = {
    /**
     * Repo Url
     * URL to a downloadable ZIP of the repository (e.g., GitHub archive link).
     */
    repo_url?: string | null;
    /**
     * Branch
     * Branch to use if repo_url is a GitHub repository link.
     */
    branch?: string | null;
    /**
     * Zip File Form Param
     */
    zip_file_form_param?: unknown;
};

/**
 * ErrorResponse
 */
export type ErrorResponse = {
    /**
     * Detail
     */
    detail: string;
};

/**
 * FileData
 */
export type FileData = {
    /**
     * Path
     */
    path: string;
    /**
     * Content
     */
    content: string;
};

/**
 * GraphEdge
 */
export type GraphEdge = {
    /**
     * Source
     */
    source: string;
    /**
     * Target
     */
    target: string;
    /**
     * Relationship
     */
    relationship: string;
};

/**
 * GraphNode
 */
export type GraphNode = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Category
     */
    category: string;
    /**
     * File
     */
    file?: string | null;
    /**
     * Start Line
     */
    start_line?: number | null;
    /**
     * End Line
     */
    end_line?: number | null;
    /**
     * Code
     */
    code?: string | null;
};

/**
 * GraphResponse
 */
export type GraphResponse = {
    /**
     * Html Url
     */
    html_url: string;
    /**
     * Nodes
     */
    nodes: Array<GraphNode>;
    /**
     * Edges
     */
    edges: Array<GraphEdge>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * StructureResponse
 */
export type StructureResponse = {
    /**
     * Directory Tree
     */
    directory_tree: string;
    /**
     * Files
     */
    files: Array<FileData>;
};

/**
 * TextResponse
 */
export type TextResponse = {
    /**
     * Text Content
     */
    text_content: string;
    /**
     * Filename Suggestion
     */
    filename_suggestion: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type GenerateTextEndpointApiGenerateTextPostData = {
    body?: BodyGenerateTextEndpointApiGenerateTextPost;
    path?: never;
    query?: never;
    url: '/api/generate-text';
};

export type GenerateTextEndpointApiGenerateTextPostErrors = {
    /**
     * Invalid input (e.g., no URL or ZIP).
     */
    400: ErrorResponse;
    /**
     * Could not download or no suitable files found.
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Server error during processing.
     */
    500: ErrorResponse;
};

export type GenerateTextEndpointApiGenerateTextPostError = GenerateTextEndpointApiGenerateTextPostErrors[keyof GenerateTextEndpointApiGenerateTextPostErrors];

export type GenerateTextEndpointApiGenerateTextPostResponses = {
    /**
     * Repository content as JSON.
     */
    200: TextResponse;
};

export type GenerateTextEndpointApiGenerateTextPostResponse = GenerateTextEndpointApiGenerateTextPostResponses[keyof GenerateTextEndpointApiGenerateTextPostResponses];

export type GenerateGraphEndpointApiGenerateGraphPostData = {
    body?: BodyGenerateGraphEndpointApiGenerateGraphPost;
    path?: never;
    query?: never;
    url: '/api/generate-graph';
};

export type GenerateGraphEndpointApiGenerateGraphPostErrors = {
    /**
     * Invalid input.
     */
    400: ErrorResponse;
    /**
     * Not found or no suitable files.
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Server error.
     */
    500: ErrorResponse;
};

export type GenerateGraphEndpointApiGenerateGraphPostError = GenerateGraphEndpointApiGenerateGraphPostErrors[keyof GenerateGraphEndpointApiGenerateGraphPostErrors];

export type GenerateGraphEndpointApiGenerateGraphPostResponses = {
    /**
     * JSON containing graph nodes, edges, and URL to an HTML visualization.
     */
    200: GraphResponse;
};

export type GenerateGraphEndpointApiGenerateGraphPostResponse = GenerateGraphEndpointApiGenerateGraphPostResponses[keyof GenerateGraphEndpointApiGenerateGraphPostResponses];

export type GenerateStructureEndpointApiGenerateStructurePostData = {
    body?: BodyGenerateStructureEndpointApiGenerateStructurePost;
    path?: never;
    query?: never;
    url: '/api/generate-structure';
};

export type GenerateStructureEndpointApiGenerateStructurePostErrors = {
    /**
     * Invalid input.
     */
    400: ErrorResponse;
    /**
     * Not found or no suitable files.
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Server error.
     */
    500: ErrorResponse;
};

export type GenerateStructureEndpointApiGenerateStructurePostError = GenerateStructureEndpointApiGenerateStructurePostErrors[keyof GenerateStructureEndpointApiGenerateStructurePostErrors];

export type GenerateStructureEndpointApiGenerateStructurePostResponses = {
    /**
     * Repository structure and content as JSON.
     */
    200: StructureResponse;
};

export type GenerateStructureEndpointApiGenerateStructurePostResponse = GenerateStructureEndpointApiGenerateStructurePostResponses[keyof GenerateStructureEndpointApiGenerateStructurePostResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:8003' | (string & {});
};